# Data Structures

In the following notebook I will give a brief overview of the main data structures in Julia. Namely:

 - Arrays
 - Vectors
 - Matrices
 - Tuples
 - Dictionaries
 - Sets
 ***
As I didn't want to make this notebook too long, I decided to leave out more advanced data structures, which will be presented in another Notebook. 

## Arrays

In Julia there are 2 main ways to create arrays:
 - Array{T,N}(undef, dims) --> Type (T) and Dimension (N) explicilty given
 - Array{T}(undef, dims) --> N is implicitly derived by the lenght of dims


In [8]:
A = Array{Float64, 2}(undef, 2, 3) # N=2 (given explicitly)

2×3 Matrix{Float64}:
 2.2398e-314  2.2398e-314  2.33891e-314
 0.0          0.0          0.0

In [4]:
B = Array{Float64}(undef, 4) # N=1 (given implicitly)

4-element Vector{Float64}:
 1.603e-319
 5.3756030174002e-299
 2.121996045e-314
 2.151614564e-314

In [10]:
C = Array{Float64}(undef,2,2,2) #N=3 )(given implicitly)

2×2×2 Array{Float64, 3}:
[:, :, 1] =
 2.21921e-314  2.21921e-314
 2.21921e-314  2.21921e-314

[:, :, 2] =
 2.21921e-314  2.21921e-314
 2.21921e-314  2.21921e-314

**Note**: Vectors and Matrices are Arrays(Vector and Matrices are basically one and 2 dimensional aliases for arrays) . Thus:
- If the array has 1 dimension, it will be stored as "vector"
- If the array has 2 dimension, it will be stored as "matrix"
- If the array has 3+ dimensions, it will be stored as "array"
***
Arrays can ave an arbitraty number of dimensions and cal also store other arrays. The inner arrays do not have to have the same dimension.

In [14]:
#Creating an array of arrays
numbers = [[1,2,4],[4,5],[9,11,12,14,50]]

3-element Vector{Vector{Int64}}:
 [1, 2, 4]
 [4, 5]
 [9, 11, 12, 14, 50]

In [44]:
#Arrays can contain objects of any arbitrary type:
a = ["Economics" 2; 3.1     true]

2×2 Matrix{Any}:
  "Economics"     2
 3.1           true

**Note**: Arrays can be accessed via indexing and they can be  modified using:
 - push! -> adds an element to the end of an array
 - pop!  -> removes the last element of an array
 
**Important** In the Julia programming language:
- ! at the end of a function chenges the opearand of the function. 


Ex: push(a,2) will not change a but push!(a,2) will

***
Array proprierties can be retrieved using: ndims(), size(), lenght(), axes()

In [22]:
#accessing an array via indexing
a[1,1]

"Economics"

In [47]:
#The presence of an element in an array can be checked by using the in operator 
2 in a # returns true
in(2,a) # same as above
4 in a # returns false

false

In [23]:
a = [1,2]
push!(a, 30,40,50) #adds 30,40,50 to array a
pop!(a) #removes 50 from a
a

4-element Vector{Int64}:
  1
  2
 30
 40

In [25]:
# Arrays properties
ndims(a) # number of dimensions of a
size(a) # size of each dimension of a
length(a) # length (factor of the sizes) of a
axes(a) # axes of a

(Base.OneTo(4),)

**A fundamental property of arrays is that, in Julia, they are passed by reference.** This means that two arrays that have been made equal point out to the same data in memory and that changing one array changes the other as well.

In [27]:
a = ["My string" 2; 3.1 true]
b=a #b points to the same object in memory as a
a[1,1] = "Example of passing by reference" #changing a changes b
b[1, 1]

"Example of passing by reference"

In [28]:
# This can be easily checked by the typing
pointer_from_objref(a) == pointer_from_objref(b)

true

In [29]:
#if we want to make sure that b is not changed when a is changes:
b = copy(a)

2×2 Matrix{Any}:
  "Example of passing by reference"     2
 3.1                                 true

In [30]:
#= In addition to copy() , Julia has a deepcopy() function
While copy() does not change possible references to other objects within the array 
(for example, an array inside the array and which is still passed by reference), deepcopy() does.
=#
a = [1 2 3]
b = ["My String", a]
c = copy(b)
d = deepcopy(b)
a[1] = 45
c[2] # results 45 2 3 
d[2] # results 1 2 3

1×3 Matrix{Int64}:
 1  2  3

## Vectors
***
As previously mentioned, vectors are one dimensional arrays

#### Creating Vectors

In [31]:
#Creating Vectors
a = [1, 2, 3] # vector --> Vector{Int64} (alias for Array{Int64, 1})
a = [1; 2; 3] # same vector

3-element Vector{Int64}:
 1
 2
 3

**Note**: if we omit the commas or the semicolon we create matrices

In [36]:
b = [1 2 3] # 1x3 matrix (i.e., row vector)
b = [1 2 3]' # 3x1 matrix (i.e., column vector)

3×1 adjoint(::Matrix{Int64}) with eltype Int64:
 1
 2
 3

In [37]:
# A faster command to created vectors is:
a = collect(1.0:0.5:4) # vector from 1.0 to 4.0 with step 0.5

7-element Vector{Float64}:
 1.0
 1.5
 2.0
 2.5
 3.0
 3.5
 4.0

In [38]:
#Similarly, Julia has step range constructors
a = 1:5:1 # list of points from i to j with step n
a = range(1, 5, length=2) # linearly spaced list of k points

1.0:4.0:5.0

In [39]:
#the steps range constructors can be converted into vectors by calling the collect() funciton
a = collect(a) # creates a vector

2-element Vector{Float64}:
 1.0
 5.0

In [40]:
# collect() is a generator that allows the use of general programming structures such as loops or conditionals
collect(x for x in 1:10 if isodd(x))

5-element Vector{Int64}:
 1
 3
 5
 7
 9

#### Basic Functions and Operations on Vectors

In [41]:
#A related and versatile function is enumerate, which returns an index of a collection
a = ["micro", "macro", "econometrics"];
for (index, value) in enumerate(a)
    println("$index $value") # Prints
end

1 micro
2 macro
3 econometrics


In [42]:
#The basic operators to manipulate vectors include:
show(a) # shows a sum(a) # sum of a
maximum(a) # max of a
minimum(a) # min of a
a[end] # gets last element of a
a[end-1] # gets element of a -1

["micro", "macro", "econometrics"]

"macro"

In [43]:
#Sorting Vectors
a = [2,1,3]
sort(a) # sorts a
sort(a,by=abs) # sorts a by absolute values 
sortperm(a) # indices of sort of a
first(a) # returns 2 
last(a) # returns 3
findall(isodd,a) # returns indices of occurrences (here 2,3) 
findfirst(isodd,a) # returns first index of occurrence

2

In [48]:
# Julia also defines set operations
a = [2,1,3]
b = [2,4,5]
union(a,b) # returns 2,1,3,4,5
intersect(a,b) # returns 2 setdiff(a,b) # returns 1,3 setdiff(b,a) # returns 4,5

1-element Vector{Int64}:
 2

## Matrices

**Basic Commands**

In [49]:
a=[12;34] #createa2x2matrix a[2, 2] # access element 2,2 a[1, :] # access first row
a[:, 1] # access first column
a = zeros(2,2) # zero matrix
a = ones(2,2) # unitary matrix
a = fill(2,3,4) # fill a 3x4 matrix with 2's
a = trues(2,2) # 2x2 matrix of trues
a = falses(2,2) # 2x2 matrix of falses
a = rand(2,2) # random matrix (uniform) a = randn(2,2) # random matrix (gaussian)

2×2 Matrix{Float64}:
 0.206188  0.069475
 0.218301  0.517598

In [50]:
#If we want to repeat a matrix to take advantage of some inner structure:
a=[1 2;3 4] #createa2x2matrix
b = repeat(a, 2,3) # repeats matrix 2x3 times --> we get a 4x6 matrix

4×6 Matrix{Int64}:
 1  2  1  2  1  2
 3  4  3  4  3  4
 1  2  1  2  1  2
 3  4  3  4  3  4

#### Basic Operations

In [93]:
using LinearAlgebra

#Some Matrix Operations
a = [1 2;3 4]
b = [1 2;3 4]
a' # complex conjugate transpose of a
a[:] # convert matrix a to vector
vec(a) # vectorization of a
a*a # multiplication of two matrices
a\a # solution of linear system ax = b
inv(a) # inverse of a
pinv(a) # pseudo-inverse of a 
rank(a) # rank of a
norm(a) # Euclidean norm of a
det(a) # determinant of a
#trace(a) # trace of a
eigen(a) # eigenvalues and eigenvectors tril(a) # lower triangular matrix of a
triu(a) # upper triangular matrix of a
rotr90(a,1) # rotate a 90 degrees n = 1 times
rot180(a,2) # rotate a 180 degrees n = 2 times
cat(a,b; dims = 1) # concatenate a and b along dimension i = 0
a = [[1 2] [1 2]] # concatenate horizontally
hcat([1 2],[1 2]) # alternative notation to above
a = [[1 2]; [1 2]] # concatenate vertically
vcat([1 2],[1 2]) # alternative notation to above
a = diagm(0=>[1; 2; 3]) # diagonal matrix
a = reshape(1:10, 5, 2) # reshape

5×2 reshape(::UnitRange{Int64}, 5, 2) with eltype Int64:
 1   6
 2   7
 3   8
 4   9
 5  10

In [94]:
#A powerful (but tricky!) function is broadcast() , which extends a 
#non-conforming matrix to the required dimensions in a function:
a = [1,2]
b = [1 2;3 4]
broadcast(+,a,b) # returns [2 3;5 6]

2×2 Matrix{Int64}:
 2  3
 5  6

## Tuples
***
Data type of that contains an ordered collection of elements. The elements of a tuple cannot be changed once they have been defined.

In [95]:
a = ("This is a tuple", 2018) # definition of a tuple
a[2] # accessing element 2 of tuple a

2018

### Dictionaries
***
Most convenient to deal with large sets of text. 

**Unlike tuples and arrats, dictionaries ar enot ordered. So, we can't index into them.**

In [99]:
# Creating a dictionary
a = Dict("University of Pennsylvania" => "Philadelphia", "Boston College" =>
    "Boston")
a["University of Pennsylvania"] # access one key
a["Harvard"] = "Cambridge" # adds an additional key delete!(a,"Harvard") # deletes a key
keys(a)
values(a)
haskey(a,"University of Pennsylvania") # returns true 
haskey(a,"MIT") # returns false

false

In [100]:
# We can get a value and simultaneously remove it from the dictionary by using the pop! function #

println(pop!(a, "Harvard"))
a

Cambridge


Dict{String, String} with 2 entries:
  "University of Pennsylvania" => "Philadelphia"
  "Boston College"             => "Boston"

### Sets
***
Set are collection of unique elements. 
 - Different from arrays because sets are unordered collections of unique elements (the order of elements is strictly remembered in Arrays)
 - Each element in a set must be unique. 
 - Sets are mutable data types

In [101]:
Set2 = Set([1, 2, 3, 4, 5, 2, 4, 6])
println(Set2)

Set([5, 4, 6, 2, 3, 1])


In [107]:
#Set items cannot be accessed by referring to an index value (sets are unordered the items have no fixed index)
Set2[1] #returns error message

LoadError: MethodError: no method matching getindex(::Set{Int64}, ::Int64)

In [108]:
# However, you can loop through the set items using a for loop
for i in Set2
    println(i)
end

#or ask if a specified value is present in a set
in(10, Set2)

5
4
6
2
3
1


false